FROM python:3.7
EXPOSE 8501
#RUN pip install -r requirements.txt
#RUN pip install streamlit
#RUN pipenv shell
#RUN pip install pipenv
#RUN pipenv install --system --deploy
RUN chmod 777 run.sh
RUN chmod 777 install.sh
RUN ./install.sh
#COPY . .
